config/routes.rb
Rails.application.routes.draw do
  resources :mains
  resources :users
  resources :menus
  resources :carts
  resources :order_items
  resources :menu_items
  resources :orders
  get "/home_page", to: "sessions#index"
  post "/add_to_cart", to: "carts#create", as: :create_cart
  get "/", to: "home#index"
  get "/signin", to: "sessions#new", as: :new_sessions
  post "/signin", to: "sessions#create", as: :sessions
  delete "/signout", to: "sessions#destroy", as: :destroy_session
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  belongs_to :menu
  has_many :carts
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  before_action :set_menu_item, only: [:show, :edit, :update, :destroy]

  # GET /menu_items
  # GET /menu_items.json
  def index
    @menu_items = MenuItem.all
    @current_menu_id = Menu.find_by(active: true).id
    @current_menu_id = params[:current_menu_id] if params[:current_menu_id]
  end

  # GET /menu_items/1
  # GET /menu_items/1.json
  def show
  end

  # GET /menu_items/new
  def new
    @menu_item = MenuItem.new
    @current_menu_id = params[:current_menu_id] if params[:current_menu_id]
  end

  # GET /menu_items/1/edit
  def edit
  end

  # POST /menu_items
  # POST /menu_items.json
  def create
    MenuItem.create!(
      menu_id: params[:menu_id],
      menu_item_name: params[:menu_item_name],
      menu_item_price: params[:menu_item_price],
      stock: params[:stock],
    )
    redirect_to menu_items_path
  end

  # PATCH/PUT /menu_items/1
  # PATCH/PUT /menu_items/1.json
  def update
    respond_to do |format|
      if @menu_item.update(menu_item_params)
        format.html { redirect_to @menu_item, notice: "Menu item was successfully updated." }
        format.json { render :show, status: :ok, location: @menu_item }
      else
        format.html { render :edit }
        format.json { render json: @menu_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menu_items/1
  # DELETE /menu_items/1.json
  def destroy
    @menu_item.destroy
    respond_to do |format|
      format.html { redirect_to menu_items_url, notice: "Menu item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_menu_item
    @menu_item = MenuItem.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def menu_item_params
    params.require(:menu_item).permit(:menu_id, :menu_item_name, :menu_item_price, :stock)
  end
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/views/menu_items/_display_menu.html.erb
<% MenuItem.joins(:menu).where("menu_id = ?",menu_id).each do |item| %> 
  <%= form_with url: create_cart_path do |form| %>
    <div class="Menu-items">
      <p class="Menu-item-name">  <%= item.menu_item_name%> </p>
      <p class="Menu-item-name">  <%= item.menu_item_price %> </p>
      <%= hidden_field_tag 'menu_item_id',item.id%>
      <%= hidden_field_tag 'menu_id',item.menu_id%>
      <%= hidden_field_tag 'user_id', @current_user.id %>
    </div>
  <% end %>
<% end %>

app/views/menu_items/_form.html.erb
<%= form_with(model: menu_item, local: true) do |form| %>
  <% if menu_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(menu_item.errors.count, "error") %> prohibited this menu_item from being saved:</h2>

      <ul>
        <% menu_item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.hidden_field :menu_id , :value => @current_menu_id %>
  </div>

  <div class="field">
    <%= form.label :menu_item_name %>
    <%= form.text_field :menu_item_name %>
  </div>

  <div class="field">
    <%= form.label :menu_item_price %>
    <%= form.text_field :menu_item_price %>
  </div>

  <div class="field">
    <%= form.label :stock %>
    <%= form.number_field :stock %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/menu_items/_select_menu.html.erb
<%= form_with url: menu_items_path, method: "GET" do |form| %>
    <%= select_tag "current_menu_id",
        options_from_collection_for_select(Menu.all,"id","menu_name",menu_id),
        :onchange => "submit()"    
    %>
<% end %>

app/views/menu_items/edit.html.erb
<h1>Editing Menu Item</h1>

<%= render 'form', menu_item: @menu_item %>

<%= link_to 'Show', @menu_item %> |
<%= link_to 'Back', menu_items_path %>

app/views/menu_items/index.html.erb
<p id="notice"><%= notice %></p>
   
<% if @current_user.role =="owner"%>
    <%= render partial: "select_menu",
        locals: { 
            menu_id: @current_menu_id
        } 
    %>
<% end %>

<%= render partial: "display_menu",
    locals: { 
        menu_id: @current_menu_id 
    } 
%>

<% if @current_user.role =="owner"%>
<%= link_to 'Add Menu Item', new_menu_item_path(:current_menu_id => @current_menu_id) 
%>
<% end %>

app/views/menu_items/new.html.erb
<section class="MenuItem">  
    <h1 class="MenuItem-add"> Add Menu Item   </h1>    
    <section class="UsersNew">
        <%= form_with url: menu_items_path do |form| %>
            <%= hidden_field_tag 'menu_id', @current_menu_id%>
            <div class="Form-section">
                <p class="FormInput-label">Menu Item Name </p>
                <%= form.text_field :menu_item_name , class: "Form-input" %>
            </div>
            <div class="Form-section">
                <p class="FormInput-label">Menu Item Price </p>
                <%= form.text_field :menu_item_price , class: "Form-input" %>
            </div>
            <div class="Form-section">
                <p class="FormInput-label"> Stock </p>
                <%= form.text_field :stock , class: "Form-input" %>
            </div>
            <div class="Form-section">
                <%= form.submit "Add Item ", class: "Form-submit"%>
            </div>
        <% end %>
    </section>
</section>

app/views/menu_items/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Menu Items</h1>

<table>
  <thead>
    <tr>
      <th>Menu</th>
      <th>Menu item name</th>
      <th>Menu item price</th>
      <th>Stock</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @menu_items.each do |menu_item| %>
      <tr>
        <td><%= menu_item.menu_id %></td>
        <td><%= menu_item.menu_item_name %></td>
        <td><%= menu_item.menu_item_price %></td>
        <td><%= menu_item.stock %></td>
        <% if @current_user.role == 'owner'%>
          <td><%= link_to 'Edit', edit_menu_item_path(menu_item) %></td>
          <td><%= link_to 'Destroy', menu_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
       
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if @current_user.role == 'owner'%>
  <%= link_to 'New Menu Item', new_menu_item_path %>
<% end %>
      