config/routes.rb
Rails.application.routes.draw do
  resources :mains
  resources :users
  resources :menus
  resources :carts
  resources :order_items
  resources :menu_items
  resources :orders
  get "/home_page", to: "sessions#index"
  post "/add_to_cart", to: "carts#create", as: :create_cart
  get "/", to: "home#index"
  get "/signin", to: "sessions#new", as: :new_sessions
  post "/signin", to: "sessions#create", as: :sessions
  delete "/signout", to: "sessions#destroy", as: :destroy_session
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :menu
  belongs_to :menu_item
  belongs_to :user
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    cart = Cart.find_by(user_id: params[:user_id],
                        menu_item_id: params[:menu_item_id])
    if cart == nil
      Cart.create!(
        user_id: params[:user_id],
        menu_item_id: params[:menu_item_id],
        menu_id: params[:menu_id],
        quantity: params[:quantity],
      )
    else
      if params[:quantity].to_i == 0
        cart.destroy
      else
        cart.quantity = params[:quantity]
        cart.save
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: "Cart was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_cart
    @cart = Cart.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def cart_params
    params.require(:cart).permit(:user_id, :menu_item_id, :quantity, :menu_id)
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
        <% cart.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :menu_item_id %>
    <%= form.text_field :menu_item_id %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="field">
    <%= form.label :menu_id %>
    <%= form.text_field :menu_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Menu item</th>
      <th>Quantity</th>
      <th>Menu</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% Cart.where(user_id: @current_user.id).each do |cart| %>
      <tr>
        <td><%= cart.user_id %></td>
        <td><%= cart.menu_item_id %></td>
        <td><%= cart.quantity %></td>
        <td><%= cart.menu_id %></td>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= form_with url: orders_path do %>  
  <%= button_tag 'Place Order' , :onclick => "submit()" %>
<% end %>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @cart.user_id %>
</p>

<p>
  <strong>Menu item:</strong>
  <%= @cart.menu_item_id %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @cart.quantity %>
</p>

<p>
  <strong>Menu:</strong>
  <%= @cart.menu_id %>
</p>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>